// Property readers for every defaults type shown in the gallery.
//
// The gallery cannot rely on `Diagnosticable.debugFillProperties`: release
// builds (e.g. the web build) report no properties and minified type names.

import 'package:flutter/material.dart';

/// The type name and the properties of a defaults object, in declaration
/// order. Returns null for a type the gallery does not know.
(String, Map<String, Object?>)? propertiesOf(Object value) {
  return switch (value) {
    final ButtonStyle v => (
      'ButtonStyle',
      <String, Object?>{
        'textStyle': v.textStyle,
        'backgroundColor': v.backgroundColor,
        'foregroundColor': v.foregroundColor,
        'overlayColor': v.overlayColor,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'elevation': v.elevation,
        'padding': v.padding,
        'minimumSize': v.minimumSize,
        'fixedSize': v.fixedSize,
        'maximumSize': v.maximumSize,
        'iconColor': v.iconColor,
        'iconSize': v.iconSize,
        'iconAlignment': v.iconAlignment,
        'side': v.side,
        'shape': v.shape,
        'mouseCursor': v.mouseCursor,
        'visualDensity': v.visualDensity,
        'tapTargetSize': v.tapTargetSize,
        'animationDuration': v.animationDuration,
        'enableFeedback': v.enableFeedback,
        'alignment': v.alignment,
        'backgroundBuilder': v.backgroundBuilder,
        'foregroundBuilder': v.foregroundBuilder,
        'splashFactory': v.splashFactory,
      },
    ),
    final FloatingActionButtonThemeData v => (
      'FloatingActionButtonThemeData',
      <String, Object?>{
        'foregroundColor': v.foregroundColor,
        'backgroundColor': v.backgroundColor,
        'focusColor': v.focusColor,
        'hoverColor': v.hoverColor,
        'splashColor': v.splashColor,
        'elevation': v.elevation,
        'focusElevation': v.focusElevation,
        'hoverElevation': v.hoverElevation,
        'disabledElevation': v.disabledElevation,
        'highlightElevation': v.highlightElevation,
        'shape': v.shape,
        'enableFeedback': v.enableFeedback,
        'iconSize': v.iconSize,
        'sizeConstraints': v.sizeConstraints,
        'smallSizeConstraints': v.smallSizeConstraints,
        'largeSizeConstraints': v.largeSizeConstraints,
        'extendedSizeConstraints': v.extendedSizeConstraints,
        'extendedIconLabelSpacing': v.extendedIconLabelSpacing,
        'extendedPadding': v.extendedPadding,
        'extendedTextStyle': v.extendedTextStyle,
        'mouseCursor': v.mouseCursor,
      },
    ),
    final SegmentedButtonThemeData v => (
      'SegmentedButtonThemeData',
      <String, Object?>{'style': v.style},
    ),
    final CardThemeData v => (
      'CardThemeData',
      <String, Object?>{
        'clipBehavior': v.clipBehavior,
        'color': v.color,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'elevation': v.elevation,
        'margin': v.margin,
        'shape': v.shape,
      },
    ),
    final DialogThemeData v => (
      'DialogThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'elevation': v.elevation,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'shape': v.shape,
        'alignment': v.alignment,
        'iconColor': v.iconColor,
        'titleTextStyle': v.titleTextStyle,
        'contentTextStyle': v.contentTextStyle,
        'actionsPadding': v.actionsPadding,
        'barrierColor': v.barrierColor,
        'insetPadding': v.insetPadding,
        'clipBehavior': v.clipBehavior,
        'constraints': v.constraints,
      },
    ),
    final BottomSheetThemeData v => (
      'BottomSheetThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'surfaceTintColor': v.surfaceTintColor,
        'elevation': v.elevation,
        'modalBackgroundColor': v.modalBackgroundColor,
        'shadowColor': v.shadowColor,
        'modalBarrierColor': v.modalBarrierColor,
        'modalElevation': v.modalElevation,
        'shape': v.shape,
        'showDragHandle': v.showDragHandle,
        'dragHandleColor': v.dragHandleColor,
        'dragHandleSize': v.dragHandleSize,
        'clipBehavior': v.clipBehavior,
        'constraints': v.constraints,
      },
    ),
    final SnackBarThemeData v => (
      'SnackBarThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'actionTextColor': v.actionTextColor,
        'disabledActionTextColor': v.disabledActionTextColor,
        'contentTextStyle': v.contentTextStyle,
        'elevation': v.elevation,
        'shape': v.shape,
        'behavior': v.behavior,
        'width': v.width,
        'insetPadding': v.insetPadding,
        'showCloseIcon': v.showCloseIcon,
        'closeIconColor': v.closeIconColor,
        'actionOverflowThreshold': v.actionOverflowThreshold,
        'actionBackgroundColor': v.actionBackgroundColor,
        'disabledActionBackgroundColor': v.disabledActionBackgroundColor,
        'dismissDirection': v.dismissDirection,
      },
    ),
    final MaterialBannerThemeData v => (
      'MaterialBannerThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'surfaceTintColor': v.surfaceTintColor,
        'shadowColor': v.shadowColor,
        'dividerColor': v.dividerColor,
        'contentTextStyle': v.contentTextStyle,
        'elevation': v.elevation,
        'padding': v.padding,
        'leadingPadding': v.leadingPadding,
      },
    ),
    final DividerThemeData v => (
      'DividerThemeData',
      <String, Object?>{
        'color': v.color,
        'space': v.space,
        'thickness': v.thickness,
        'indent': v.indent,
        'endIndent': v.endIndent,
        'radius': v.radius,
      },
    ),
    final ListTileThemeData v => (
      'ListTileThemeData',
      <String, Object?>{
        'dense': v.dense,
        'shape': v.shape,
        'style': v.style,
        'selectedColor': v.selectedColor,
        'iconColor': v.iconColor,
        'textColor': v.textColor,
        'titleTextStyle': v.titleTextStyle,
        'subtitleTextStyle': v.subtitleTextStyle,
        'leadingAndTrailingTextStyle': v.leadingAndTrailingTextStyle,
        'contentPadding': v.contentPadding,
        'tileColor': v.tileColor,
        'selectedTileColor': v.selectedTileColor,
        'horizontalTitleGap': v.horizontalTitleGap,
        'minVerticalPadding': v.minVerticalPadding,
        'minLeadingWidth': v.minLeadingWidth,
        'minTileHeight': v.minTileHeight,
        'enableFeedback': v.enableFeedback,
        'mouseCursor': v.mouseCursor,
        'visualDensity': v.visualDensity,
        'titleAlignment': v.titleAlignment,
        'controlAffinity': v.controlAffinity,
        'isThreeLine': v.isThreeLine,
      },
    ),
    final ExpansionTileThemeData v => (
      'ExpansionTileThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'collapsedBackgroundColor': v.collapsedBackgroundColor,
        'tilePadding': v.tilePadding,
        'expandedAlignment': v.expandedAlignment,
        'childrenPadding': v.childrenPadding,
        'iconColor': v.iconColor,
        'collapsedIconColor': v.collapsedIconColor,
        'textColor': v.textColor,
        'collapsedTextColor': v.collapsedTextColor,
        'shape': v.shape,
        'collapsedShape': v.collapsedShape,
        'clipBehavior': v.clipBehavior,
        'expansionAnimationStyle': v.expansionAnimationStyle,
      },
    ),
    final ChipThemeData v => (
      'ChipThemeData',
      <String, Object?>{
        'color': v.color,
        'backgroundColor': v.backgroundColor,
        'deleteIconColor': v.deleteIconColor,
        'disabledColor': v.disabledColor,
        'selectedColor': v.selectedColor,
        'secondarySelectedColor': v.secondarySelectedColor,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'selectedShadowColor': v.selectedShadowColor,
        'showCheckmark': v.showCheckmark,
        'labelPadding': v.labelPadding,
        'padding': v.padding,
        'side': v.side,
        'shape': v.shape,
        'labelStyle': v.labelStyle,
        'secondaryLabelStyle': v.secondaryLabelStyle,
        'brightness': v.brightness,
        'elevation': v.elevation,
        'pressElevation': v.pressElevation,
        'iconTheme': v.iconTheme,
        'avatarBoxConstraints': v.avatarBoxConstraints,
        'deleteIconBoxConstraints': v.deleteIconBoxConstraints,
        'checkmarkColor': v.checkmarkColor,
      },
    ),
    final InputDecorationThemeData v => (
      'InputDecorationThemeData',
      <String, Object?>{
        'labelStyle': v.labelStyle,
        'floatingLabelStyle': v.floatingLabelStyle,
        'helperStyle': v.helperStyle,
        'helperMaxLines': v.helperMaxLines,
        'hintStyle': v.hintStyle,
        'hintFadeDuration': v.hintFadeDuration,
        'hintMaxLines': v.hintMaxLines,
        'errorStyle': v.errorStyle,
        'errorMaxLines': v.errorMaxLines,
        'floatingLabelBehavior': v.floatingLabelBehavior,
        'floatingLabelAlignment': v.floatingLabelAlignment,
        'isDense': v.isDense,
        'contentPadding': v.contentPadding,
        'isCollapsed': v.isCollapsed,
        'iconColor': v.iconColor,
        'prefixIconColor': v.prefixIconColor,
        'prefixIconConstraints': v.prefixIconConstraints,
        'prefixStyle': v.prefixStyle,
        'suffixIconColor': v.suffixIconColor,
        'suffixIconConstraints': v.suffixIconConstraints,
        'suffixStyle': v.suffixStyle,
        'counterStyle': v.counterStyle,
        'filled': v.filled,
        'fillColor': v.fillColor,
        'activeIndicatorBorder': v.activeIndicatorBorder,
        'outlineBorder': v.outlineBorder,
        'focusColor': v.focusColor,
        'hoverColor': v.hoverColor,
        'errorBorder': v.errorBorder,
        'focusedBorder': v.focusedBorder,
        'focusedErrorBorder': v.focusedErrorBorder,
        'disabledBorder': v.disabledBorder,
        'enabledBorder': v.enabledBorder,
        'border': v.border,
        'alignLabelWithHint': v.alignLabelWithHint,
        'constraints': v.constraints,
        'visualDensity': v.visualDensity,
      },
    ),
    final CheckboxThemeData v => (
      'CheckboxThemeData',
      <String, Object?>{
        'mouseCursor': v.mouseCursor,
        'fillColor': v.fillColor,
        'checkColor': v.checkColor,
        'overlayColor': v.overlayColor,
        'splashRadius': v.splashRadius,
        'materialTapTargetSize': v.materialTapTargetSize,
        'visualDensity': v.visualDensity,
        'shape': v.shape,
        'side': v.side,
      },
    ),
    final RadioThemeData v => (
      'RadioThemeData',
      <String, Object?>{
        'mouseCursor': v.mouseCursor,
        'fillColor': v.fillColor,
        'overlayColor': v.overlayColor,
        'splashRadius': v.splashRadius,
        'materialTapTargetSize': v.materialTapTargetSize,
        'visualDensity': v.visualDensity,
        'backgroundColor': v.backgroundColor,
        'side': v.side,
        'innerRadius': v.innerRadius,
      },
    ),
    final SwitchThemeData v => (
      'SwitchThemeData',
      <String, Object?>{
        'thumbColor': v.thumbColor,
        'trackColor': v.trackColor,
        'trackOutlineColor': v.trackOutlineColor,
        'trackOutlineWidth': v.trackOutlineWidth,
        'materialTapTargetSize': v.materialTapTargetSize,
        'mouseCursor': v.mouseCursor,
        'overlayColor': v.overlayColor,
        'splashRadius': v.splashRadius,
        'thumbIcon': v.thumbIcon,
        'padding': v.padding,
      },
    ),
    final SliderThemeData v => (
      'SliderThemeData',
      <String, Object?>{
        'trackHeight': v.trackHeight,
        'activeTrackColor': v.activeTrackColor,
        'inactiveTrackColor': v.inactiveTrackColor,
        'secondaryActiveTrackColor': v.secondaryActiveTrackColor,
        'disabledActiveTrackColor': v.disabledActiveTrackColor,
        'disabledInactiveTrackColor': v.disabledInactiveTrackColor,
        'disabledSecondaryActiveTrackColor':
            v.disabledSecondaryActiveTrackColor,
        'activeTickMarkColor': v.activeTickMarkColor,
        'inactiveTickMarkColor': v.inactiveTickMarkColor,
        'disabledActiveTickMarkColor': v.disabledActiveTickMarkColor,
        'disabledInactiveTickMarkColor': v.disabledInactiveTickMarkColor,
        'thumbColor': v.thumbColor,
        'overlappingShapeStrokeColor': v.overlappingShapeStrokeColor,
        'disabledThumbColor': v.disabledThumbColor,
        'overlayColor': v.overlayColor,
        'valueIndicatorColor': v.valueIndicatorColor,
        'valueIndicatorStrokeColor': v.valueIndicatorStrokeColor,
        'overlayShape': v.overlayShape,
        'tickMarkShape': v.tickMarkShape,
        'thumbShape': v.thumbShape,
        'trackShape': v.trackShape,
        'valueIndicatorShape': v.valueIndicatorShape,
        'rangeTickMarkShape': v.rangeTickMarkShape,
        'rangeThumbShape': v.rangeThumbShape,
        'rangeTrackShape': v.rangeTrackShape,
        'rangeValueIndicatorShape': v.rangeValueIndicatorShape,
        'showValueIndicator': v.showValueIndicator,
        'valueIndicatorTextStyle': v.valueIndicatorTextStyle,
        'minThumbSeparation': v.minThumbSeparation,
        'thumbSelector': v.thumbSelector,
        'mouseCursor': v.mouseCursor,
        'allowedInteraction': v.allowedInteraction,
        'padding': v.padding,
        'thumbSize': v.thumbSize,
        'trackGap': v.trackGap,
      },
    ),
    final SearchBarThemeData v => (
      'SearchBarThemeData',
      <String, Object?>{
        'elevation': v.elevation,
        'backgroundColor': v.backgroundColor,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'overlayColor': v.overlayColor,
        'side': v.side,
        'shape': v.shape,
        'padding': v.padding,
        'textStyle': v.textStyle,
        'hintStyle': v.hintStyle,
        'constraints': v.constraints,
        'textCapitalization': v.textCapitalization,
      },
    ),
    final SearchViewThemeData v => (
      'SearchViewThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'elevation': v.elevation,
        'surfaceTintColor': v.surfaceTintColor,
        'side': v.side,
        'shape': v.shape,
        'headerHeight': v.headerHeight,
        'headerTextStyle': v.headerTextStyle,
        'headerHintStyle': v.headerHintStyle,
        'constraints': v.constraints,
        'padding': v.padding,
        'barPadding': v.barPadding,
        'shrinkWrap': v.shrinkWrap,
        'dividerColor': v.dividerColor,
      },
    ),
    final DatePickerThemeData v => (
      'DatePickerThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'elevation': v.elevation,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'shape': v.shape,
        'headerBackgroundColor': v.headerBackgroundColor,
        'headerForegroundColor': v.headerForegroundColor,
        'headerHeadlineStyle': v.headerHeadlineStyle,
        'headerHelpStyle': v.headerHelpStyle,
        'dayStyle': v.dayStyle,
        'dayForegroundColor': v.dayForegroundColor,
        'dayBackgroundColor': v.dayBackgroundColor,
        'dayOverlayColor': v.dayOverlayColor,
        'dayShape': v.dayShape,
        'todayForegroundColor': v.todayForegroundColor,
        'todayBackgroundColor': v.todayBackgroundColor,
        'todayBorder': v.todayBorder,
        'yearStyle': v.yearStyle,
        'yearForegroundColor': v.yearForegroundColor,
        'yearBackgroundColor': v.yearBackgroundColor,
        'yearOverlayColor': v.yearOverlayColor,
        'yearShape': v.yearShape,
        'rangePickerBackgroundColor': v.rangePickerBackgroundColor,
        'rangePickerElevation': v.rangePickerElevation,
        'rangePickerShadowColor': v.rangePickerShadowColor,
        'rangePickerSurfaceTintColor': v.rangePickerSurfaceTintColor,
        'rangePickerShape': v.rangePickerShape,
        'rangePickerHeaderBackgroundColor': v.rangePickerHeaderBackgroundColor,
        'rangePickerHeaderForegroundColor': v.rangePickerHeaderForegroundColor,
        'rangePickerHeaderHeadlineStyle': v.rangePickerHeaderHeadlineStyle,
        'rangePickerHeaderHelpStyle': v.rangePickerHeaderHelpStyle,
        'rangeSelectionBackgroundColor': v.rangeSelectionBackgroundColor,
        'rangeSelectionOverlayColor': v.rangeSelectionOverlayColor,
        'dividerColor': v.dividerColor,
        'inputDecorationTheme': v.inputDecorationTheme,
        'cancelButtonStyle': v.cancelButtonStyle,
        'confirmButtonStyle': v.confirmButtonStyle,
        'locale': v.locale,
        'toggleButtonTextStyle': v.toggleButtonTextStyle,
        'subHeaderForegroundColor': v.subHeaderForegroundColor,
        'weekdayStyle': v.weekdayStyle,
      },
    ),
    final AppBarThemeData v => (
      'AppBarThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'foregroundColor': v.foregroundColor,
        'elevation': v.elevation,
        'scrolledUnderElevation': v.scrolledUnderElevation,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'shape': v.shape,
        'iconTheme': v.iconTheme,
        'actionsIconTheme': v.actionsIconTheme,
        'centerTitle': v.centerTitle,
        'titleSpacing': v.titleSpacing,
        'leadingWidth': v.leadingWidth,
        'toolbarHeight': v.toolbarHeight,
        'toolbarTextStyle': v.toolbarTextStyle,
        'titleTextStyle': v.titleTextStyle,
        'systemOverlayStyle': v.systemOverlayStyle,
        'actionsPadding': v.actionsPadding,
      },
    ),
    final BottomAppBarThemeData v => (
      'BottomAppBarThemeData',
      <String, Object?>{
        'color': v.color,
        'elevation': v.elevation,
        'shape': v.shape,
        'height': v.height,
        'surfaceTintColor': v.surfaceTintColor,
        'shadowColor': v.shadowColor,
        'padding': v.padding,
      },
    ),
    final NavigationBarThemeData v => (
      'NavigationBarThemeData',
      <String, Object?>{
        'height': v.height,
        'backgroundColor': v.backgroundColor,
        'elevation': v.elevation,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'indicatorColor': v.indicatorColor,
        'indicatorShape': v.indicatorShape,
        'labelTextStyle': v.labelTextStyle,
        'iconTheme': v.iconTheme,
        'labelBehavior': v.labelBehavior,
        'overlayColor': v.overlayColor,
        'labelPadding': v.labelPadding,
      },
    ),
    final NavigationRailThemeData v => (
      'NavigationRailThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'elevation': v.elevation,
        'unselectedLabelTextStyle': v.unselectedLabelTextStyle,
        'selectedLabelTextStyle': v.selectedLabelTextStyle,
        'unselectedIconTheme': v.unselectedIconTheme,
        'selectedIconTheme': v.selectedIconTheme,
        'groupAlignment': v.groupAlignment,
        'labelType': v.labelType,
        'useIndicator': v.useIndicator,
        'indicatorColor': v.indicatorColor,
        'indicatorShape': v.indicatorShape,
        'minWidth': v.minWidth,
        'minExtendedWidth': v.minExtendedWidth,
      },
    ),
    final NavigationDrawerThemeData v => (
      'NavigationDrawerThemeData',
      <String, Object?>{
        'tileHeight': v.tileHeight,
        'backgroundColor': v.backgroundColor,
        'elevation': v.elevation,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'indicatorColor': v.indicatorColor,
        'indicatorShape': v.indicatorShape,
        'indicatorSize': v.indicatorSize,
        'labelTextStyle': v.labelTextStyle,
        'iconTheme': v.iconTheme,
      },
    ),
    final DrawerThemeData v => (
      'DrawerThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'scrimColor': v.scrimColor,
        'elevation': v.elevation,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'shape': v.shape,
        'endShape': v.endShape,
        'width': v.width,
        'clipBehavior': v.clipBehavior,
      },
    ),
    final TabBarThemeData v => (
      'TabBarThemeData',
      <String, Object?>{
        'indicator': v.indicator,
        'indicatorColor': v.indicatorColor,
        'indicatorSize': v.indicatorSize,
        'dividerColor': v.dividerColor,
        'dividerHeight': v.dividerHeight,
        'labelColor': v.labelColor,
        'labelPadding': v.labelPadding,
        'labelStyle': v.labelStyle,
        'unselectedLabelColor': v.unselectedLabelColor,
        'unselectedLabelStyle': v.unselectedLabelStyle,
        'overlayColor': v.overlayColor,
        'splashFactory': v.splashFactory,
        'mouseCursor': v.mouseCursor,
        'tabAlignment': v.tabAlignment,
        'textScaler': v.textScaler,
        'indicatorAnimation': v.indicatorAnimation,
        'splashBorderRadius': v.splashBorderRadius,
      },
    ),
    final MenuStyle v => (
      'MenuStyle',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'elevation': v.elevation,
        'padding': v.padding,
        'minimumSize': v.minimumSize,
        'fixedSize': v.fixedSize,
        'maximumSize': v.maximumSize,
        'side': v.side,
        'shape': v.shape,
        'mouseCursor': v.mouseCursor,
        'visualDensity': v.visualDensity,
        'alignment': v.alignment,
      },
    ),
    final PopupMenuThemeData v => (
      'PopupMenuThemeData',
      <String, Object?>{
        'color': v.color,
        'shape': v.shape,
        'menuPadding': v.menuPadding,
        'elevation': v.elevation,
        'shadowColor': v.shadowColor,
        'surfaceTintColor': v.surfaceTintColor,
        'textStyle': v.textStyle,
        'labelTextStyle': v.labelTextStyle,
        'enableFeedback': v.enableFeedback,
        'mouseCursor': v.mouseCursor,
        'position': v.position,
        'iconColor': v.iconColor,
        'iconSize': v.iconSize,
      },
    ),
    final BadgeThemeData v => (
      'BadgeThemeData',
      <String, Object?>{
        'backgroundColor': v.backgroundColor,
        'textColor': v.textColor,
        'smallSize': v.smallSize,
        'largeSize': v.largeSize,
        'textStyle': v.textStyle,
        'padding': v.padding,
        'alignment': v.alignment,
        'offset': v.offset,
      },
    ),
    final ProgressIndicatorThemeData v => (
      'ProgressIndicatorThemeData',
      <String, Object?>{
        'color': v.color,
        'linearTrackColor': v.linearTrackColor,
        'linearMinHeight': v.linearMinHeight,
        'circularTrackColor': v.circularTrackColor,
        'refreshBackgroundColor': v.refreshBackgroundColor,
        'borderRadius': v.borderRadius,
        'stopIndicatorColor': v.stopIndicatorColor,
        'stopIndicatorRadius': v.stopIndicatorRadius,
        'strokeWidth': v.strokeWidth,
        'strokeAlign': v.strokeAlign,
        'strokeCap': v.strokeCap,
        'constraints': v.constraints,
        'trackGap': v.trackGap,
        'circularTrackPadding': v.circularTrackPadding,
        'controller': v.controller,
      },
    ),
    _ => null,
  };
}
